services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - mqtt
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=CurrentData
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=MyPass@word
      - DOCKER_INFLUXDB_INIT_ORG=iot
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyToken

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-dashboard-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=MyPass@word

configs:
  mosquitto_config:
    file: ./mosquitto.conf
