services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:mqtt
    command: sleep infinity

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - mqtt
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=CurrentData
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=MyPass@word
      - DOCKER_INFLUXDB_INIT_ORG=iot
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyToken

  opcplc:
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    ports:
      - "50000:50000"
      - "8080:8080"
    command: >
      --pn=50000
      --autoaccept
      --sph
      --sn=5
      --sr=10
      --st=uint
      --fn=5
      --fr=1
      --ft=uint
      --gn=5
      --aa
      --ut

configs:
  mosquitto_config:
    file: ./mosquitto.conf
